# Generated by Django 5.2.10 on 2026-01-17 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0007_alter_product_unitofmeasure'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranType', models.CharField(choices=[('S', 'Sales'), ('P', 'Purchase')], max_length=1)),
                ('tranDate', models.DateField()),
                ('one_time_name', models.CharField(blank=True, max_length=250, null=True)),
                ('one_time_number', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('grossAmount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.customer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.supplier')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transactionheader')),
            ],
        ),
    ]
