# Generated by Django 5.2.10 on 2026-01-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionheader',
            name='paymentMode',
            field=models.CharField(choices=[('C', 'Cash'), ('A', 'Card'), ('T', 'Bank Transfer'), ('U', 'UPI')], default='C', max_length=1),
        ),
    ]
