# Generated by Django 5.2.9 on 2025-12-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobileNo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='mobileNo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
