# Generated by Django 5.2.9 on 2025-12-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_alter_customer_mobileno_alter_supplier_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='companyName',
            field=models.CharField(default='DummyName', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='officeNo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='officeNo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
