# Generated by Django 5.2.9 on 2025-12-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_alter_customer_companyname_alter_customer_officeno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='companyName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='officeNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='officeNo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
