# Generated by Django 5.2.9 on 2026-01-01 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_alter_customer_companyname_alter_customer_officeno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productCategory', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('currentStock', models.DecimalField(decimal_places=2, max_digits=7)),
                ('unitOfMeasure', models.CharField(choices=[('PCS', 'Pieces'), (' MTR', 'Meter')], default='MTR', max_length=5)),
                ('reOrderlLevel', models.DecimalField(decimal_places=2, max_digits=7)),
                ('productCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.productcategory')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
