# Generated by Django 5.2.9 on 2026-01-01 21:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_productcategory_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barCode',
            field=models.CharField(default=django.utils.timezone.now, max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='purchasePrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='product',
            name='salesPrice',
            field=models.DecimalField(decimal_places=2, default=12345, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='currentStock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='reOrderlLevel',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
    ]
