# Generated by Django 5.2.10 on 2026-01-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_product_barcode_product_purchaseprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unitOfMeasure',
            field=models.CharField(choices=[('PCS', 'Pieces'), ('MTR', 'Meter')], default='MTR', max_length=5),
        ),
    ]
